[project]
name = "asl-sign-language-detection"
requires-python = ">=3.11,<3.13"

[tool.poetry]
name = "asl-sign-language-detection"
version = "1.0.0"
description = "ASL Sign Language Detection System"

[tool.poetry.dependencies]
python = "^3.11"
